services:
  airsonic-advanced:
    image: lscr.io/linuxserver/airsonic-advanced:latest
    container_name: airsonic-advanced
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - CONTEXT_PATH= # optional
      - JAVA_OPTS= # optional
    volumes:
      - /ach/volumes/airsonic-advanced:/config
      - /ach/media/music:/music
      - /ach/media/airsonic-advanced/playlists:/playlists
      - /ach/media/airsonic-advanced/podcasts:/podcasts
    ports:
      - "4040:4040"
    restart: unless-stopped