services:
  airsonic-advanced:
    image: lscr.io/linuxserver/airsonic-advanced:latest
    container_name: airsonic-advanced
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
      # Optional:
      # CONTEXT_PATH: /airsonic
      # JAVA_OPTS: "-Xms512m -Xmx2g"
    volumes:
      - /path/volumes/airsonic-advanced:/config
      - /path/media/airsonic-advanced/music:/music:ro
      - /path/media/airsonic-advanced/playlists:/playlists
      - /path/media/airsonic-advanced/podcasts:/podcasts
    ports:
      - "4040:4040"
    restart: unless-stopped