services:
  process-exporter:
    image: ncabatoff/process-exporter:latest
    container_name: process-exporter
    restart: unless-stopped
    command:
      - "--procfs=/host/proc"
      - "--config.path=/config/process-exporter.yml"
      - "--web.listen-address=:9256"
    ports:
      - "9256:9256"
    volumes:
      - /proc:/host/proc:ro
      - /path/compose/process-exporter/process-exporter.yml:/config/process-exporter.yml:ro
    networks:
      - monitoring

networks:
  monitoring:
    external: true