global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "<IP>:<Port>"

  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "<IP>:<Port>"

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "<IP>:<Port>"

  # ✅ Docker Engine / Daemon Metrics
  - job_name: "docker-engine"
    static_configs:
      - targets:
          - "<IP>:<Port>"

  - job_name: "nut"
    metrics_path: /ups_metrics
    params:
      ups: ["ups"]
    static_configs:
      - targets:
          - "<IP>:<Port>"
        labels:
          ups: "ups"

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://grafana.example.com
          - https://prometheus.example.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <IP>:<Port>

  - job_name: "smartctl"
    static_configs:
      - targets:
          - "<IP>:<Port>"

  - job_name: "process-exporter"
    static_configs:
      - targets:
          - "<IP>:<Port>"

  # ✅ NEW: Loki internal metrics
  - job_name: "loki"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "<IP>:<Port>"
