services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - /ach/volumes/vaultwarden:/data:rw
    environment:
      - ADMIN_TOKEN=
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true
      - SMTP_HOST=
      - SMTP_FROM=
      - SMTP_SECURITY=
      - SMTP_PORT=587
      - SMTP_SSL=true
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - DOMAIN=