- Social:
    - VRC:
        - icon: /icons/VRLogo.png
          href: 
    - Steam:
        - icon: /icons/steam.svg
          href: 

    - bluesky:
        - icon: /icons/bluesky.svg
          href: 

    - Ihearthis:
        - icon: /icons/ihear.png
          href: 

    - VRCDN:
        - icon: /icons/VRCDN.png
          href: