services:
  diun:
    image: crazymax/diun:latest
    command: serve
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Paris"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      # Discord notification settings
      - "DIUN_NOTIF_DISCORD_WEBHOOKURL=<>"
      - "DIUN_NOTIF_DISCORD_MENTIONS=<>"
      - "DIUN_NOTIF_DISCORD_RENDERFIELDS=true"
      - "DIUN_NOTIF_DISCORD_TIMEOUT=10s"
      - "DIUN_NOTIF_DISCORD_TEMPLATEBODY=Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released."
    labels:
      - "diun.enable=true"
    restart: always